### ISSUE TITLE
Double quotes being rendered in HTML as &quot;

### ISSUE THREAD

**Issue by Deimos** [github/cmark-gfm#130]
I'm not sure at exactly which version this started happening (I can try to narrow it down if needed), but I recently updated from cmark-gfm 0.28.0.gfm.11 to 0.28.3.gfm.19, and I've noticed that the behavior of double-quote characters (`"`) has changed and is now being rendered to HTML as `&quot;` instead of staying as a simple `"`.

The code gives me the impression that this isn't deliberate behavior, since that entity is an exception in the tests here: https://github.com/github/cmark-gfm/blob/master/test/entity_tests.py#L39

Was this a deliberate change and/or did it come from upstream? It doesn't really hurt anything for me, but I thought it might be worth bringing up.

**Comment by kivikakk** [comment]
Hrm; I believe this has been the behaviour for a long time, including the version you moved from:

```console
sencha ~/github/cmark$ build/src/cmark-gfm --version
cmark 0.28.0.gfm.11 - CommonMark converter
(C) 2014-2016 John MacFarlane
sencha ~/github/cmark$ build/src/cmark-gfm <<<'"'
<p>&quot;</p>
```

It's been this way at least since Feb 2015 when this test was added (upstream, before the cmark-gfm fork): https://github.com/github/cmark-gfm/commit/2f4cbcb9957a2840735a547cc846eeb566262a44. This dates it to cmark 0.18, but possibly even earlier.

**Comment by Deimos** [comment]
Huh, strange. The reason I noticed it is because after upgrading, I wrote a script to re-process all my site's old comments to check for differences in the rendered HTML, and a lot of them were coming up exactly the same except with `"` replaced with `&quot;`.

It's possible that it could be related to something else in my setup and not cmark-gfm specifically though. Do you think it's worth me looking into more? If not, feel free to close this (and thanks for checking into it and the quick response).

**Comment by kivikakk** [comment]
That's super strange! Has anything else in your setup changed? Are you calling the `cmark-gfm` binary directly, or are you using a wrapper library? (Something that might be post-processing the output which used to convert some entities into their literal characters and now isn't?) I'm definitely open to the possibility that there's some explanation implicating `cmark-gfm` directly, but so far it looks like this has been consistent.

**Comment by Deimos** [comment]
Yeah, it's very possible something else changed it and I didn't notice the difference until I happened to update cmark-gfm. Thanks for humoring me, I'll consider this my fault.

**Comment by kivikakk** [comment]
Happy to (attempt to) help! ❤️

**Comment by Deimos** [comment]
Sorry to continue pestering you with this one, but I ran into something else today that made me more certain that it was specifically cmark-gfm's behavior that changed. I think the tricky bit is that when you tested 0.28.0.gfm.11 above, that version was re-released on August 9, along with every version from 0.27.1.gfm.2 up to 0.28.3.gfm.14.

I was previously using the original 0.28.0.gfm.11 from *before* that re-release, so I think the behavior must have changed as part of the re-release. From a quick look, I can't really see anything - what caused all of those versions to be re-released and replaced on August 9?

Anyway, this isn't really important overall, I've just continued being curious about it and wanted to try to solve a little more of this mystery when I ran into it again today.

**Comment by kivikakk** [comment]
Hey, thanks for checking back in.

>I think the tricky bit is that when you tested 0.28.0.gfm.11 above, that version was re-released on August 9, along with every version from 0.27.1.gfm.2 up to 0.28.3.gfm.14.

This is not quite accurate -- the "release" in the GitHub sense was indeed authored on those dates, which is to say I copied the relevant part of the changelog into https://github.com/github/cmark-gfm/releases/tag/0.28.0.gfm.11, but you'll notice the commit https://github.com/github/cmark-gfm/commit/e3f3a27ba1762f7acfc9881369fee737f8f73386 that release/tag is attached to is indeed made September 2017. I try to create the associated release with each tag as I go, but I forget sometimes and then go back later and fill them all in, as was the case here 😅

**Comment by Deimos** [comment]
Hmm. Something else must have happened too then, because the main reason I knew about the re-release is that the sha256sum of the 0.28.0.gfm.11 release .tar.gz file changed at some point: https://gitlab.com/tildes/tildes/issues/299

It was originally `a95ee221c3f6d718bbb38bede95f05f05e07827f8f3c29ed6cb09ddb7d05c2cd` but changed to `8100698cd6fa4e3d870d9c7fbf92ef795a60ea3d7b00e3a4d1904105b1191fae`.

I originally updated to 0.28.0.gfm.11 on 2017-11-12 and noted the sha256 at that point, but I'm not sure specifically when it changed, all I know is sometime before 2018-10-17.

**Comment by kivikakk** [comment]
That is very strange, and I'm not sure what to make of it. It's possible something in our archive-producing service has changed in the time since, causing the sha256 to change, but in general we'd avoid such changes for exactly this reason.

The only other possible explanation is that the commit that tag pointed to changed. It's unfortunate that git doesn't version tag changes, but I consulted our server-side git logs to determine when the tag was created, and sure enough:

```json
[
  {
    "time": "2017-09-11T15:37:56.000-07:00",
    "user_login": "kivikakk",
    "targets": [
      {
        "ref": "refs/tags/0.28.0.gfm.11",
        "before": "0000000000000000000000000000000000000000",
        "after": "50087c8bd3be7738af4868b77f7f85ba1127afca"
      }
    ]
  }
]
```

The listed SHA1 is the sha of the annotated tag object itself, which we can confirm with `git rev-parse`:

```console
$ git show 50087c8bd3be7738af4868b77f7f85ba1127afca
tag 0.28.0.gfm.11
Tagger: Ashe Connor <ashe@kivikakk.ee>
Date:   Tue Sep 12 08:37:46 2017 +1000

0.28.0.gfm.11
-----BEGIN PGP SIGNATURE-----

iQIcBAABCgAGBQJZtxA6AAoJEESj0sleJrsU1/0P/1umsvj5ooUzcV1NXtTC7PEL
sr5QnPiYHLl+CjQrpJZApkDyfXspZztMArgSrn76DXvIDjhLnSQrcr8h3SjRPVMU
K1+pOEgqy7O5mJeoL2821Lbi+3pKDpXCTsaKVcqXFdwmkdpG9iGk3vO0UqNPvo9K
8+2DJBUs2Eqd7u8+8fIBP0l3iCZD6mEgr56YKRqaXBZFcIhc5m7odKdgyqYAPKos
YJL3f/RPUnrLQUR1YUWtQIPtINypUm1pptJpxnxIIaBJf+uHfjDkh/lWXLJ2wfGt
1XD0ShW91VvtRny+43AKgJ+htvRejPI4jx0zKNJG3A+L0KlwbVNLUSko2CMuO3m5
ZzLrRH6XYPMbLPEEpOaA2YKswwB5L4ZASVERQ02yT7AlKGcs2bHZ9mlFTxKzrLRQ
EgIL8KpSgrXIqRZzplbhJDpJy3FCXMkzxMIMbGj5D04A/WPxJ+fQN7wx+nRleKZJ
NxfBp9AfBTy7HgGg2VcbkPVUTdn1b+g2nnrlkRjx0ZA366U5h4p1LnxBpFgVfkWf
3u8sw0G2ordW75yALqcekGaek5Wj2DNMmqvULYd+nI+j5ZpTCIreXggImP1T9+ZF
PmjfsRBaEFl2oOROWRqq6oO0MezuoW0HdwzW9pWzNX/pp2J6DLpLQtQQZaPyxhq+
QC4eoPTAm0LDPDvZTiBj
=RbcQ
-----END PGP SIGNATURE-----

commit e3f3a27ba1762f7acfc9881369fee737f8f73386 (HEAD, tag: 0.28.0.gfm.11)
Author: Ashe Connor <ashe@kivikakk.ee>
Date:   Tue Sep 12 08:37:44 2017 +1000

    0.28.0.gfm.11

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 1b461a5..1b8a5e8 100755
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -19,7 +19,7 @@ set(PROJECT_NAME "cmark")
 set(PROJECT_VERSION_MAJOR 0)
 set(PROJECT_VERSION_MINOR 28)
 set(PROJECT_VERSION_PATCH 0)
-set(PROJECT_VERSION_GFM 10)
+set(PROJECT_VERSION_GFM 11)
 set(PROJECT_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.gfm.${PROJECT_VERSION_GFM} )

 option(CMARK_TESTS "Build cmark tests and enable testing" ON)
diff --git a/changelog.txt b/changelog.txt
index bef3f2b..5203776 100644
--- a/changelog.txt
+++ b/changelog.txt
@@ -1,3 +1,7 @@
+[0.28.0.gfm.11]
+
+  * Do not output empty `<tbody>` in table extension.
+
 [0.28.0.gfm.10]

   * Fix denial of service parsing references.
$ git rev-parse 50087c8bd3be7738af4868b77f7f85ba1127afca^0
e3f3a27ba1762f7acfc9881369fee737f8f73386
$
```

So, while I can't speak to why the sha256 of the tar.gz has changed, I can say with confidence that the commit the tag has pointed to has been unchanged since its creation.

**Comment by Deimos** [comment]
Huh, very strange. Well, thanks very much again for the time and effort helping me dig into this confusing but unimportant question. I really appreciate it, and I promise I won't come back a third time about it. :sweat_smile:

**Comment by waldyrious** [comment]
I believe the changing sha256sum for github releases might be related to the issue discussed in https://github.com/libgit2/libgit2/issues/4343 (and the threads linked thereof).

**Comment by kivikakk** [comment]
Wow, fun thread. @waldyrious Thanks for the link, that's super useful for me as a library maintainer to know 👍

**Comment by waldyrious** [comment]
Glad to have helped :)
