### ISSUE TITLE
[Request] Image Size Issues

### ISSUE THREAD

**Issue by maxswjeon** [github/cmark-gfm#131]
There is no way to resize images if they are bigger than wrapper width. There were some ways to resize them by pipe or additional curly braces (https://gist.github.com/uupaa/f77d2bcf4dc7a294d109)
Is there any further plans for image resizing?

**Comment by kivikakk** [comment]
:wave: There are no plans to modify the core Markdown syntax for images at present. This change would need to be made in [CommonMark](https://github.com/commonmark/CommonMark) first. Right now writing out the `<img>` tag yourself is the only way to do this.
