### ISSUE TITLE
Nested task lists parsed in a strange way

### ISSUE THREAD

**Issue by mity** [github/cmark-gfm#134]
From [CommonMark spec 0.28](https://spec.commonmark.org/0.28/#list-items):

>  If a sequence of lines Ls constitute a sequence of blocks Bs starting with a non-whitespace character and not separated from each other by more than one blank line, and M is a list marker of width W followed by 1 ≤ N ≤ 4 spaces, then the result of prepending M and the following spaces to the first line of Ls, and indenting subsequent lines of Ls by W + N spaces, is a list item with Bs as its contents. The type of the list item (bullet or ordered) is determined by the type of its list marker. If the list item is ordered, then it is also assigned a start number, based on the ordered list marker.

I'd more or less assume this nice property should be preserved even for task lists. But in some cases it is not. 

Consider this example, first for the ordinary lists.

```
 * * * foo
```
which is translated to
```
<ul>
   <li><ul>
      <li><ul>
         <li>foo</li>
      </ul></li>
   </ul></li>
</ul>
```

And compare it with the task lists:

```
 * [x] * [ ] * [x] foo
```

Here only the topmost tak list item is recognized. The nested lists (ordinary lists or task lists) are not recognized at all:

```
<ul class="contains-task-list">
   <li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> * [ ] * [x] foo</li>
</ul>
```

Is it intended behavior?

**Comment by kivikakk** [comment]
I consider this behaviour intended, although it is underspecified. It parses the same as does `* x * y * z`, which is to say the _task list item marker_ is separate to the list marker, and so stops repeated processing of the block in that manner.

**Comment by mity** [comment]
Ok. Thanks.
