### ISSUE TITLE
Description List

### ISSUE THREAD

**Issue by cup** [github/cmark-gfm#135]
if you put this markdown on github.com:

~~~
one two
: three four five six
~~~

it gives you the expected output with github.io:

~~~html
<dl>
  <dt>one two</dt>
  <dd>three four five six</dd>
</dl>
~~~

but not with github.com:

~~~html
<p>one two
: three four five six</p>
~~~

this is because github.io uses KramDown by default, which supports
Description Lists:

https://kramdown.gettalong.org/syntax#definition-lists

while github.com uses GFM:

https://github.github.com/gfm

github.io can be configured to use `CommonMarkGhPages` which would give it the
same output as github.com. however that is not ideal because then both sites
would be producing the errant output. better would be if GFM supported
Description Lists as well. References:

- https://developer.mozilla.org/Web/HTML/Element/dl
- https://meta.stackexchange.com/questions/72395

**Comment by cup** [comment]
https://github.com/commonmark/cmark/issues/281

**Comment by kivikakk** [comment]
Support for description lists is not planned for GFM; if it lands in upstream CommonMark (per commonmark/cmark#281), then will will absorb it, but at this time no changes to the GFM extensions to CommonMark are being made.
