### ISSUE TITLE
Multiple footnotes

### ISSUE THREAD

**Issue by allenwu1973** [github/cmark-gfm#139]
Hi

I found adding multiple footnote reference together, without space, does not work in cmark-gfm.
This does work in pandoc and kramdown.

Thank you

```
This is my test [^ref1][^ref2].

[^ref1]: some ref
[^ref2]: other ref
```

**Comment by allenwu1973** [comment]
Here is a naive patch that seems to fix this, not sure if this the right thing to do.

```diff
diff --git a/src/inlines.c b/src/inlines.c
index 63caeeb..5d27ebf 100644
--- a/src/inlines.c
+++ b/src/inlines.c
@@ -1137,7 +1137,14 @@ noMatch:
       inl->as.literal = cmark_chunk_dup(literal, 1, literal->len - 1);
       inl->start_line = inl->end_line = subj->line;
       inl->start_column = opener->inl_text->start_column;
+
+      // A footnote reference cannot have labels
+      if (found_label) {
+        subj->pos = initial_pos;
+      }
+
       inl->end_column = subj->pos + subj->column_offset + subj->block_offset;
```

**Comment by phillmv** [comment]
I independently came to this same conclusion and roughly the same patch! This just got merged in, cheers.

**Comment by waldyrious** [comment]
> I independently came to this same conclusion and roughly the same patch! This just got merged in, cheers.

For additional context, see https://github.com/github/cmark-gfm/pull/229#discussion_r694049803.
