### ISSUE TITLE
Autolink extension is underspecified

### ISSUE THREAD

**Issue by waldyrious** [github/cmark-gfm#146]
The [spec of the Autolinks extension](https://github.github.com/gfm/#autolinks-extension-) says:

> When an autolink ends in `)`, we scan the entire autolink for the total number of parentheses. If there is a greater number of closing parentheses than opening ones, we don’t consider the last character part of the autolink

Instead of "the last character", it probably should say something like "the unmatched trailing parentheses", which more accurately describes the current implementation.

There are two examples provided in the spec, `www.google.com/search?q=Markup+(business)` and `(www.google.com/search?q=Markup+(business))`, which demonstrate the handling of a single unmatched closing parenthesis, but the case with multiple unmatched parentheses, e.g. `(www.google.com/search?q=Markup+(business)))`, is left unspecified.

If there's interest, I'm happy to send a PR updating the [relevant text](https://github.com/github/cmark-gfm/blob/87c0139ee1213528f4f24e08e6844d261b8d0f1b/test/spec.txt#L9244-L9245).

**Comment by kivikakk** [comment]
By all means, please do send a PR! I'll propagate it to the spec shown at https://github.github.com/gfm/.
