### ISSUE TITLE
GFM valid domain is too unspecified

### ISSUE THREAD

**Issue by johelegp** [github/cmark-gfm#149]
> A [valid domain](https://github.github.com/gfm/#valid-domain) consists of alphanumeric characters, underscores (_), hyphens (-) and periods (.). There must be at least one period, and no underscores may be present in the last two segments of the domain.

What are segments? It seems to refer to the components of a [domain name](https://en.wikipedia.org/wiki/Domain_name) (top-level domain, second-level domain, etc.). It seems that the intention is for a _valid domain_ to consist of at least 2 `.`-separated identifiers made up of alphanumeric characters, underscores (_) and hyphens (-), except that the last 2 may have no underscore.

**Comment by kivikakk** [comment]
PRs happily accepted to address this and #150. Unfortunately I don't have much in the way of time for resolving these ambiguities/underspecifications.
