### ISSUE TITLE
Possibly wrong CMARK_STATIC_DEFINE and  CMARKEXTENSIONS_STATIC_DEFINE macro names

### ISSUE THREAD

**Issue by karen-arutyunov** [github/cmark-gfm#156]
While packaging cmark-gfm libraried for build2 toolchain, I have noticed that src/CMakeLists.txt defines CMARK_STATIC_DEFINE and CMARKEXTENSIONS_STATIC_DEFINE macros that are never used in the source code, for example:
```
set_target_properties(${PROGRAM} PROPERTIES
  COMPILE_FLAGS "-DCMARK_STATIC_DEFINE -DCMARKEXTENSIONS_STATIC_DEFINE")
```

On the other hand, the auto-generated headers use similar but different macros:

cmark-gfm_export.h:
```
#ifdef CMARK_GFM_STATIC_DEFINE
#  define CMARK_GFM_EXPORT
#  define CMARK_GFM_NO_EXPORT
#else
...
#endif
```
cmark-gfm-extensions_export.h:
```
#ifdef CMARK_GFM_EXTENSIONS_STATIC_DEFINE
#  define CMARK_GFM_EXTENSIONS_EXPORT
#  define CMARK_GFM_EXTENSIONS_NO_EXPORT
#else
...
#endif
```
Is there a bug in src/CMakeLists.txt and it should contain the following code instead?

```
set_target_properties(${PROGRAM} PROPERTIES
  COMPILE_FLAGS "-DCMARK_GFM_STATIC_DEFINE -DCMARK_GFM_EXTENSIONS_STATIC_DEFINE")
```

**Comment by kivikakk** [comment]
Ah, yes, it absolutely should. The `GFM` infix has been lost, most likely during a merge or rebase. I'll fix this up -- thank you!
