### ISSUE TITLE
Tasklist extension to query state should return boolean 

### ISSUE THREAD

**Issue by NightFlyer** [github/cmark-gfm#160]
The current way to determine the state of a tasklist item is by using `char *cmark_gfm_extensions_get_tasklist_state(cmark_node *node)`. I think that this method is cumbersome, because it returns a string, which the caller must then check using some `strcmp` type methods. Because it returns a string, it requires that the strings never be changed in the future (otherwise code will break).

I think that it would be much better to have a function that returns a boolean, rather than a string. 

Personally, I would like to see `cmark_gfm_extensions_get_tasklist_state` replaced with:
```
bool cmark_gfm_extensions_tasklist_state_is_checked(cmark_node *node)
```
with the semantics being that if `node` is a tasklist and it's checked, then it will return true, otherwise it will return false. (If the node isn't a task, it returns `false`, because it isn't a task that is checked)

Obviously, this changes the behavior slightly, as the user would need to check whether `node` is a tasklist separate from getting the checked state, but I don't think that is unreasonable. Rather, I think that using the same code to both check whether a node is a tasklist _and_ to get the checked value seems confusing.

Personally, I would prefer that `cmark_gfm_extensions_get_tasklist_state` be removed, but that might be against your ideas of maintaining code compatibility. If so, then the new function could be added and the old marked as "deprecated" or some such.

**Comment by NightFlyer** [comment]
I forgot to mention that part of the reason for changing the method to `cmark_gfm_extensions_tasklist_state_is_checked` is because that would allow a set method like `cmark_gfm_extensions_tasklist_state_set_checked` when adding such a method as mentioned in Issue #159

**Comment by NightFlyer** [comment]
Also, returning an "unchecked" state for nodes that aren't tasklist nodes is similar to `cmark_node_get_list_tight` which returns false if the node isn't a list.

**Comment by kivikakk** [comment]
Should we close this now in light of #161?
