### ISSUE TITLE
cmark-gfm: cannot open shared object file

### ISSUE THREAD

**Issue by HelloEdit** [github/cmark-gfm#163]
Hi everyone,

I just installed cmark-gfm with `make`, `make test` and then `sudo make install`. But when I executed `cmark-gfm`, I got the following `cmark-gfm: error while loading shared libraries: libcmark-gfm-extensions.so.0.29.0.gfm.0: cannot open shared object file: No such file or directory`.
I've tried different things without success.

**Comment by kivikakk** [comment]
Is that `.so` actually being installed? Can you find it next to other cmark `.so` files in `/usr/lib` or `/usr/local/lib`? If not, we need to fix that. If so, maybe `sudo ldconfig` is required.

**Comment by HelloEdit** [comment]
It's strange, I cleaned some files and it seems to work fine. Sorry for the inconvenience >.<

**Comment by kivikakk** [comment]
I'm glad it's working for you now!

**Comment by poikilos** [comment]
@HelloEdit Please explain what you did to fix the problem. I have the problem too. I Tried a new shell, and that did not resolve the issue.

**Comment by Poikilos** [comment]
> It's strange, I cleaned some files and it seems to work fine. Sorry for the inconvenience >.<

Can you explain what you did? I still have the problem on Fedora 37.
