### ISSUE TITLE
Autolink does not recognise "ftp"

### ISSUE THREAD

**Issue by muzimuzhi** [github/cmark-gfm#177]
In [GFM Spec v0.29-gfm, sec. 6.8](https://github.github.com/gfm/#autolinks), it says
> An absolute URI, for these purposes, consists of a scheme followed by a colon (:) followed by zero or more characters other than ASCII whitespace and control characters, <, and >. If the URI includes these characters, they must be percent-encoded (e.g. %20 for a space).
> 
> For purposes of this spec, a scheme is any sequence of 2–32 characters beginning with an ASCII letter and followed by any combination of ASCII letters, digits, or the symbols plus (”+”), period (”.”), or hyphen (”-”).

Hence as I understand, a ftp uri is a valid absolute uri and will be auto-linked. But the following example fails
* usage specified in gfm sec. 6.8
input: `<ftp://tug.org/historic/systems/texlive/>`
output: <ftp://tug.org/historic/systems/texlive/>

Other form of input also fails:
* usage specified in gfm sec. 6.6
input: `[link to ftp](ftp://tug.org/historic/systems/texlive/)`
output: [link to ftp](ftp://tug.org/historic/systems/texlive/)

**Comment by mity** [comment]
I believe github.com site does some post-processing of the HTML as generated by cmark-gfm. It does quite a lot of things like e.g. changing `#123` into issue/PR links. It quite possibly can also disable links to other then whitelisted URL schemes.

Indeed, when using cmark-gfm locally on a commandline, it does support autolinks accordingly to the specs:

```
$ printf '<ftp://example.com>' | ./cmark-gfm
<p><a href="ftp://example.com">ftp://example.com</a></p>

$ printf '[link to ftp](ftp://tug.org/historic/systems/texlive/)' | ./cmark-gfm
<p><a href="ftp://tug.org/historic/systems/texlive/">link to ftp</a></p>
```

**Comment by muzimuzhi** [comment]
> Indeed, when using cmark-gfm locally on a commandline, it does support autolinks accordingly to the specs:

Yes I can reproduce the same output locally, hence will close this issue. I should probably report this problem to elsewhere.
