### ISSUE TITLE
Formal spec is outdated?

### ISSUE THREAD

**Issue by brysonreece** [github/cmark-gfm#193]
Hey there!

Looking at the formal spec for **GitHub Flavored Markdown** I don't see any reference to the `<details>` and `<summary>` functionality present when editing Markdown on GitHub (example below). Similarly, I also notice GitHub's markdown documentation is also missing references to this functionality as well.

Seeing as the formal spec indicates that it was last updated on `2019-04-06`, is it just a matter of the spec listed [here](https://github.github.com/gfm/) being outdated?

---

<details>
<summary>Details Example</summary>

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</details>

**Comment by kivikakk** [comment]
Just stopping by, I don't maintain this project any more, but `<details>` and `<summary>` are plain HTML, not part of GFM or CommonMark, and work by regular inline HTML inclusion.

**Comment by brysonreece** [comment]
Yeah, I was alluding to the fact that GitHub supports the folding of these elements in Markdown documents which I believe isn't native browser behavior.

**Comment by kivikakk** [comment]
Indeed; I was alluding to the fact that it is.

![0N1f6bmfBX](https://user-images.githubusercontent.com/1915/85476984-be75d200-b5fc-11ea-8826-862b88c413df.gif)

See more on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details).

**Comment by brysonreece** [comment]
Alright, must be the engine I'm using. Closing.
