### ISSUE TITLE
align attribute in th and td is obsolete

### ISSUE THREAD

**Issue by anonyno** [github/cmark-gfm#206]
validator.w3.org gives the error: "The align attribute on the th element is obsolete. Use CSS instead" on a simple table.

| Obsolete         | Not obsolete                  |
|------------------|-------------------------------|
| `align="left"`   | `style="text-align: left;"`   |
| `align="center"` | `style="text-align: center;"` |
| `align="right"`  | `style="text-align: right;"`  |

**Comment by Artoria2e5** [comment]
I think #86 addresses that.

**Comment by iMrDJAi** [comment]
@anonyno I think you should re-open this issue, the spec isn't updated to include this change.
