### ISSUE TITLE
Multi language page in GFM

### ISSUE THREAD

**Issue by shawnthompson** [github/cmark-gfm#243]
Is there a way to markup when creating a multi language page in GFM?

The Government of Canada is working a lot in the open these days but we have to supply all our documentation in both English and French. 

See our [gc-da11yn.github.io/README.md](https://github.com/gc-da11yn/gc-da11yn.github.io/blob/main/README.md) for an example.

We also have to make all content accessible to all users but if they use a screen reader to read the French text on our markdown pages in the proper language.

I guess we could put a `<div lang="fr">` around the text but it would be nice to have a way to do it in markdown.

Ideally we would like to see this change go as far up the markdown chain as possible, maybe I should open the issue in the cmark repo.

Thanks for all the great work you all do!

Shawn Thompson, WAS
Web Accessibility Technical Advisor

**Comment by shawnthompson** [comment]
Not sure what type of syntax.

I like the `:` in the [links] use but how would you use that with blocks of text?

This could be a problem if or **when** the Github interface starts supporting other languages (again) for their interface. A lot of `.md` files are in English. If the `<html>` for the site is set in another language, the markdown will inherit that language and not be properly read.

Please keep in mind it's not only non-sighted users who use a reader. Many other people with different disabilities can benefit from using a reader.

**Comment by shawnthompson** [comment]
I completely agree with you but the `lang` attribute has been a valid HTML component for quite some time now. 

I wouldn't want to put `aria` in markdown. 

[lang - HTML: HyperText Markup Language - MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang)

**Comment by wooorm** [comment]
Extensions to markdown are generally not discussed here btw, but in CommonMark. GFM extends CommonMark. GH isn’t actively adding things to GFM.
But, having some experience with CM/GFM, I don’t see this changing. Markdown is mostly frozen.

**Comment by shawnthompson** [comment]
I figured as much but I was hoping to get more support from GFM. I saw some talk about supporting Right to Left (RTL) languages on the CM issues but nothing on actually language of text. 

Maybe I should move this thread to the commonMark repo.

**Comment by shawnthompson** [comment]
That's interesting indeed. We can use language specific `.md` files instead of doing multiple languages on the page. Are you saying this is available now?

**Comment by wooorm** [comment]
It's not supported now. It could be cool though.

Might be somewhat complex though for GH, to work on all markdown (is an 'es.md' spanish? 'this.is.it.md' Italian?)

But you can support that on your site?

**Comment by shawnthompson** [comment]
I'm more interested on the Github web interface. We are using [11ty](https://www.11ty.dev) to build are site, it can easily be done with that.

The [lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) has specific value based on the BCP47 language code.

I'm thinking what could happen is that if the file name would be `README.fr.md` GH could add the `lang="fr"` to the existing `<article class="markdown-body entry-content container-lg" itemprop="text" lang="fr">` element it creates.

In our organization we can promote using `.lang.md` files instead of doing bilingual `README.md` files. Stick to using `HTML` as a last resort in the content.

**Comment by Crissov** [comment]
Yes, this is exactly what I meant. Smart i18n support for Readme files isn’t there yet, but it absolutely should be.

**Comment by shawnthompson** [comment]
@vassudanagunta I completely agree with you that using `<div lang="fr">` is not a hack and that's the beauty of Markdown, being able to use `html` elements inside it. We are going to adding the `div` to our `.md` files for now. Hopefully in the future there will be another way to standardize the language of a `.md` file.

I took a look at your project. It's an interesting idea, not sure if I would be able to contribute but I'll definitely pass it around to some colleagues who work in that field.

Thanks again.

**Comment by vassudanagunta** [comment]
@shawnthompson I'd appreciate that. I have much more than what's visible in that placeholder repo. If someone is interested, I can move it back onto a front burner and publish more.

Right now I'm developing a way for people to extend Markdown, RST or even define their own structured plaintext formats without writing any code. It's called *Plain Text Style Sheets*.
