### ISSUE TITLE
Allow whitespace in filepaths inside the round brackets

### ISSUE THREAD

**Issue by porg** [github/cmark-gfm#247]
## Foreword

I filed sbarex/QLMarkdown/issues/80 and it's author informed me that they use your **cmark-gfm** as their Markdown parser.

## Feature request to the cmark-gfm parser
Allow whitespace in filepaths inside the round brackets while:
* fully compliant syntax experiences no misinterpretations from this more relaxed interpretation,
* performance impact remains negligible.

At least the whitespace. If possible be as easy and relaxed as possible:
  - Everything inside the round brackets is considered being the filepath.
  - Only round brackets themselves need escaping of course.
  - Whitespace and other special characters get handled/escaped by the system automatically (specific to the filesystem — NTFS, APFS, EXT, … — or transport scheme — file/http/https — where it is in use)
  - If it does not start with a slash it is considered a relative path.

## Design Rationale
* Markdown's goal was/is an **easily human readable and writeable markup** language!
  * Having to change filenames prior usage with Markdown
    OR
  * Having to transform each ` ` to `%20` in the filename everywhere
* … contradicts both goals IMHO!

## Best Practises
* [Macdown](https://github.com/MacDownApp/macdown/) which uses [hoedown](https://github.com/hoedown/hoedown) supports this.

### Sample
```
## Images
### Filename without whitespace
![](1.png) --> Render the image inline.
### Filename with whitespace
![](1 b.png) --> Shows the raw markup language instead or rendering the image.
```

**Comment by Lemmingh** [comment]
You idea will lead to **ambiguity**.

The [CommonMark Spec](<https://spec.commonmark.org/>) has a lengthy explanation on this topic.

If would be impossible to distinguish **title** from **destination**, if spaces were allowed in **destination** type 2.

For example, how to interpret these:

```
[l i n k](w ' h ' a ' t ')

[l i n k](w ( h ) a ( t ))
```

---

When facing complex links, it's recommended to use **link destination** type 1:

```markdown
![alt](<1 b.png>)
```

**Comment by porg** [comment]
Hi Lemmingh,

thanks for pointing out that Markdown already has syntax support for `filenames with spaces.png` by wrapping the link destination part in round and angled brackets. The relevant sections of the specification are:

https://spec.commonmark.org/0.30/#links

> A link contains link text (the visible text), a link destination (the URI that is the link destination), and optionally a link title. There are two basic kinds of links in Markdown. In inline links the destination and title are given immediately after the link text. In reference links the destination and title are defined elsewhere in the document.

> A link text consists of a sequence of zero or more inline elements enclosed by square brackets ([ and ]).

> […]

> A link destination consists of either
>
> - a sequence of zero or more characters between an opening < and a closing > that contains no line endings or unescaped < or > characters, or
> 
> - a nonempty sequence of characters that does not start with <, does not include ASCII control characters or space character, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.

> […]

> An inline link consists of a link text followed immediately by a left parenthesis (, an optional link destination, an optional link title, and a right parenthesis ). 

https://spec.commonmark.org/0.30/#example-488
Markdown `[link](</my uri>)` produces HTML `<p><a href="/my%20uri">link</a></p>`

So I hereby close down this requests, and instead file at /sbarex/QLMarkdown which does not support `[link](</my uri>)` although that's part of the standard.
