### ISSUE TITLE
Footnotes in links are broken

### ISSUE THREAD

**Issue by wooorm** [github/cmark-gfm#249]
```markdown
[a [^b] c](https://example.com)

[^b]: asd
```

Renders (formatted w/ whitespace):

```html
<p dir="auto">
  <a href="https://example.com">
    a
    <sup></sup>
  </a>
  <a
    href="#user-content-fn-b"
    id="user-content-fnref-b"
    data-footnote-ref=""
    aria-describedby="footnote-label"
  >1</a>
  c
</p>
```

Rendered here:

[a [^b] c](https://example.com)

[^b]: asd

---

Expected. Either (when not using HTML parsing to sanitize): 

```html
<p>
  <a href="https://example.com">
    a
    <sup>
      <a
        href="#user-content-fn-b"
        id="user-content-fnref-b"
        data-footnote-ref=""
        aria-describedby="footnote-label"
      >1</a>
    </sup>
    c
  </a>
</p>
```

Or (when not generating footnotes in certain disallowed tags):

```html
<p>
  <a href="https://example.com">
    a [^b] c
  </a>
</p>
```

**Comment by phillmv** [comment]
You [can't have nested anchor tags](https://www.w3.org/TR/html401/struct/links.html#h-12.2.2), so this one is on your browser.[^cmark-gfm]

[^cmark-gfm]: if you examine the output in cmark-gfm, you'll find the library does in fact nest the links 😉.

**Comment by wooorm** [comment]
Yes, it is invalid.

CommonMark enforces logic to prevent it: it doesn’t allow what could be a link, when occurring around a link.
This is not the case for images, because images are fine in link.
Given that footnotes calls are similar to link labels, and implemented in the same code, why not implement the existing logic for links, too?

https://github.com/github/cmark-gfm/blob/ef1cfcb8a31de72bb951d9259bc4ac89e266975b/src/inlines.c#L1242-L1257

https://github.com/github/cmark-gfm/blob/ef1cfcb8a31de72bb951d9259bc4ac89e266975b/src/inlines.c#L1059
