### ISSUE TITLE
Footnotes reference in footnotes definition

### ISSUE THREAD

**Issue by lindeer** [github/cmark-gfm#276]
```md
Footnote 1 link[^first].

[^first]: footnote reference in footnote definition[^first]
```
current cmark-gfm(master@ef1cfcb8a31) generates:
```html
<p>Footnote 1 link<sup class="footnote-ref"><a href="#fn-first" id="fnref-first" data-footnote-ref>1</a></sup>.</p>
<section class="footnotes" data-footnotes>
<ol>
<li id="fn-first">
<p>footnote reference in footnote definition<sup class="footnote-ref"><a href="#fn-first" id="fnref-first-2" data-footnote-ref>1</a></sup> <a href="#fnref-first" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩</a> <a href="#fnref-first-2" class="footnote-backref" data-footnote-backref aria-label="Back to content">↩<sup class="footnote-ref">2</sup></a></p>
</li>
</ol>
</section>
```
is `<sup class="footnote-ref">2</sup>` in `<li id="fn-first">` correct ?

**Comment by wooorm** [comment]
Why wouldn't it be? What do you expect?

**Comment by lindeer** [comment]
Is that by design? I thought it was OK without `<sup class="footnote-ref">2</sup>`, like markdown-it-footnote, what  does that `<sup>2</sup>` mean?

**Comment by wooorm** [comment]
It’s to uniquely describe multiple backreferences (it doesn’t have to do with the call *in* the definition, in your example).

Other than being (arguably?) useful for sighted users, it is also a recommendation due to accessibility to [make all link texts unique](https://fae.disability.illinois.edu/rulesets/LINK_2/).

```markdown
Alpha[^a].

Bravo[^a].

Charlie[^a].

[^a]: Delta
```

Alpha[^a].

Bravo[^a].

Charlie[^a].

[^a]: Delta

**Comment by lindeer** [comment]
Got it, thanks, @wooorm

**Comment by lindeer** [comment]
Hi @wooorm , where could I find the syntax spec of footnote of this implementation? seems [gfm](https://github.github.com/gfm/) not updated with footnote at all? thx

**Comment by wooorm** [comment]
Hi! GH has a private repo for the spec somewhere. They don’t include footnotes there, unfortunately. There’s an issue open about this!
