### ISSUE TITLE
`cmark-gfm --version` out of sync

### ISSUE THREAD

**Issue by artcs** [github/cmark-gfm#308]
`cmark-gfm --version` still outputs `0.29.0.gfm.6` for gfm.8. Please keep `PROJECT_VERSION_GFM` in [CMakeLists.txt](https://github.com/github/cmark-gfm/blob/master/CMakeLists.txt#L7) in sync for new releases.

BTW: Any plans to get in sync with upstream cmark, which is at 30.0.3?

**Comment by phillmv** [comment]
🤦‍♀️ oops, forgot to this! You're absolutely right, that sucks.
